#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh git@gitlab-ext.galois.com
    - "./init_submodules.sh"

#-----------------------------------------------------------------------------#
#
# FPGA tests
#
#-----------------------------------------------------------------------------#
chisel_p1:
  script:
    - "source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh"
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh chisel_p1'"
  tags: ["fpga"]
  except:
    - schedules

bluespec_p1:
  script:
    - "source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh"
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh bluespec_p1'"
  tags: ["fpga"]
  except:
    - schedules

chisel_p2:
  script:
    - "source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh"
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh chisel_p2'"
  tags: ["fpga"]
  except:
    - schedules

bluespec_p2:
  script:
    - "source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh"
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh bluespec_p2'"
  tags: ["fpga"]
  except:
    - schedules


#-----------------------------------------------------------------------------#
#
# Bitstream generation tests
#
#-----------------------------------------------------------------------------#
bitstream_chisel_p1:
    script:
      - "export XILINXD_LICENSE_FILE=/opt/Xilinx"
      - "source /opt/Xilinx/Vivado/2017.4/settings64.sh"
      - "nix-shell tool-suite/shell.nix --run './setup_soc_project.sh chisel_p1'"
      - "nix-shell tool-suite/shell.nix --run './build.sh chisel_p1'"
    tags: ["bitstream"]
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - bitstreams/soc_chisel_p1.*
    only:
    - schedules

bitstream_bluespec_p1:
    script:
      - "export XILINXD_LICENSE_FILE=/opt/Xilinx"
      - "source /opt/Xilinx/Vivado/2017.4/settings64.sh"
      - "nix-shell tool-suite/shell.nix --run './setup_soc_project.sh bluespec_p1'"
      - "nix-shell tool-suite/shell.nix --run './build.sh bluespec_p1'"
    tags: ["bitstream"]
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - bitstreams/soc_bluespec_p1.*
    only:
    - schedules
    
bitstream_chisel_p2:
    script:
      - "export XILINXD_LICENSE_FILE=/opt/Xilinx"
      - "source /opt/Xilinx/Vivado/2017.4/settings64.sh"
      - "nix-shell tool-suite/shell.nix --run './setup_soc_project.sh chisel_p2'"
      - "nix-shell tool-suite/shell.nix --run './build.sh chisel_p2'"
    tags: ["bitstream"]
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - bitstreams/soc_chisel_p2.*
    only:
    - schedules

bitstream_bluespec_p2:
    script:
      - "export XILINXD_LICENSE_FILE=/opt/Xilinx"
      - "source /opt/Xilinx/Vivado/2017.4/settings64.sh"
      - "nix-shell tool-suite/shell.nix --run './setup_soc_project.sh bluespec_p2'"
      - "nix-shell tool-suite/shell.nix --run './build.sh bluespec_p2'"
    tags: ["bitstream"]
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - bitstreams/soc_bluespec_p2.*
    only:
    - schedules