cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - riscv-linux/
    - busybox/

#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab-ext.galois.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ./init_submodules.sh

#-----------------------------------------------------------------------------#
#
# FPGA tests
#
#-----------------------------------------------------------------------------#
chisel_p1:
  script:
    - "source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh"
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh chisel_p1'"
  tags: ["fpga"]
  except:
    - schedules

bluespec_p1:
  script:
    - "source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh"
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh bluespec_p1'"
  tags: ["fpga"]
  except:
    - schedules


#-----------------------------------------------------------------------------#
#
# Bitstream generation tests
#
#-----------------------------------------------------------------------------#
bitstream_chisel_p1:
    script:
      - "export XILINXD_LICENSE_FILE=/opt/Xilinx"
      - "source /opt/Xilinx/Vivado/2017.4/settings64.sh"
      - "nix-shell tool-suite/shell.nix --run './setup_soc_project.sh chisel_p1'"
      - "nix-shell tool-suite/shell.nix --run './build.sh chisel_p1'"
    tags: ["bitstream"]
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - bitstreams/soc_chisel_p1.*
            - vivado/soc_chisel_p1/soc_chisel_p1.runs/impl_1/design_1_timing_summary_routed.rpt 
            - vivado/soc_chisel_p1/soc_chisel_p1.runs/impl_1/design_1_utilization_placed.rpt 
            - vivado/soc_chisel_p1/soc_chisel_p1.runs/impl_1/design_1_power_routed.rpt 
    only:
    - schedules