#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
  - echo $PATH
  - export PATH=/opt/riscv/bin:$PATH
  - export RISCV=/opt/riscv
  - export PATH=/opt/Xilinx/Vivado/2019.1/bin:/opt/Xilinx/Vivado_Lab/2019.1/bin:$PATH
  - echo $PATH
  - ./init_submodules.sh
  - source /opt/Xilinx/Vivado_Lab/2019.1/settings64.sh
  - export XILINXD_LICENSE_FILE=/opt/Xilinx/Xilinx.lic

#-----------------------------------------------------------------------------#
#
# Verilator simulation tests
#
#-----------------------------------------------------------------------------#
sim_chisel_p1:
  script:
    - ./test_simulator.sh chisel_p1
  tags: ["verilator"]
  except:
    - schedules
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - verilator_simulators/run/Logs/chisel_p1/

sim_bluespec_p1:
  script:
    - ./test_simulator.sh bluespec_p1
  tags: ["verilator"]
  except:
    - schedules
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - verilator_simulators/run/Logs/bluespec_p1/

sim_chisel_p2:
  script:
    - ./test_simulator.sh chisel_p2
  tags: ["verilator"]
  except:
    - schedules
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - verilator_simulators/run/Logs/chisel_p2/

sim_bluespec_p2:
  script:
    - ./test_simulator.sh bluespec_p2
  tags: ["verilator"]
  except:
    - schedules
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - verilator_simulators/run/Logs/bluespec_p2/

sim_chisel_p3:
  script:
    - ./test_simulator.sh chisel_p3
  tags: ["verilator"]
  except:
    - schedules
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - verilator_simulators/run/Logs/chisel_p3/

#-----------------------------------------------------------------------------#
#
# Bitstream generation
#
#-----------------------------------------------------------------------------#
bitstream_gen_chisel_p1:
  script:
    - ./setup_soc_project.sh chisel_p1
    - ./build.sh chisel_p1
  tags: ["bitstream"]
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1 week
    paths:
      - bitstreams/soc_chisel_p1.*
      - vivado/soc_chisel_p1/soc_chisel_p1.runs/impl_1/design_1_timing_summary_routed.rpt
      - vivado/soc_chisel_p1/soc_chisel_p1.runs/impl_1/design_1_utilization_placed.rpt
      - vivado/soc_chisel_p1/soc_chisel_p1.runs/impl_1/design_1_power_routed.rpt
  only:
    variables:
      - $JOB_TYPE == "bitstream_gen_chisel_p1"

bitstream_gen_chisel_p2:
  script:
    - ./setup_soc_project.sh chisel_p2
    - ./build.sh chisel_p2
  tags: ["bitstream"]
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1 week
    paths:
      - bitstreams/soc_chisel_p2.*
      - vivado/soc_chisel_p2/soc_chisel_p2.runs/impl_1/design_1_timing_summary_routed.rpt
      - vivado/soc_chisel_p2/soc_chisel_p2.runs/impl_1/design_1_utilization_placed.rpt
      - vivado/soc_chisel_p2/soc_chisel_p2.runs/impl_1/design_1_power_routed.rpt

  only:
    variables:
      - $JOB_TYPE == "bitstream_gen_chisel_p2"

bitstream_gen_chisel_p3:
  script:
    - ./setup_soc_project.sh chisel_p3
    - ./build.sh chisel_p3
  tags: ["bitstream"]
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1 week
    paths:
      - bitstreams/soc_chisel_p3.*
      - vivado/soc_chisel_p3/soc_chisel_p3.runs/impl_1/design_1_timing_summary_routed.rpt
      - vivado/soc_chisel_p3/soc_chisel_p3.runs/impl_1/design_1_utilization_placed.rpt
      - vivado/soc_chisel_p3/soc_chisel_p3.runs/impl_1/design_1_power_routed.rpt
  only:
    variables:
      - $JOB_TYPE == "bitstream_gen_chisel_p3"

bitstream_gen_bluespec_p1:
  script:
    - ./setup_soc_project.sh bluespec_p1
    - ./build.sh bluespec_p1
  tags: ["bitstream"]
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1 week
    paths:
      - bitstreams/soc_bluespec_p1.*
      - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_timing_summary_routed.rpt
      - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_utilization_placed.rpt
      - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_power_routed.rpt
  only:
    variables:
      - $JOB_TYPE == "bitstream_gen_bluespec_p1"

bitstream_gen_bluespec_p2:
  script:
    - ./setup_soc_project.sh bluespec_p2
    - ./build.sh bluespec_p2
  tags: ["bitstream"]
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1 week
    paths:
      - bitstreams/soc_bluespec_p2.*
      - vivado/soc_bluespec_p2/soc_bluespec_p2.runs/impl_1/design_1_timing_summary_routed.rpt
      - vivado/soc_bluespec_p2/soc_bluespec_p2.runs/impl_1/design_1_utilization_placed.rpt
      - vivado/soc_bluespec_p2/soc_bluespec_p2.runs/impl_1/design_1_power_routed.rpt
  only:
    variables:
      - $JOB_TYPE == "bitstream_gen_bluespec_p2"

bitstream_gen_bluespec_p3:
  script:
    - ./setup_soc_project.sh bluespec_p3
    - ./build.sh bluespec_p3
  tags: ["bitstream"]
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1 week
    paths:
      - bitstreams/soc_bluespec_p3.*
      - vivado/soc_bluespec_p3/soc_bluespec_p3.runs/impl_1/design_1_timing_summary_routed.rpt
      - vivado/soc_bluespec_p3/soc_bluespec_p3.runs/impl_1/design_1_utilization_placed.rpt
      - vivado/soc_bluespec_p3/soc_bluespec_p3.runs/impl_1/design_1_power_routed.rpt
  only:
    variables:
      - $JOB_TYPE == "bitstream_gen_bluespec_p3"

#-----------------------------------------------------------------------------#
#
# FPGA tests
#
#-----------------------------------------------------------------------------#
bluespec_p1:
  script:
    - ./test_processor.sh bluespec_p1 #--full_ci
  tags: ["fpga"]
#  only:
#    - develop
  except:
    - schedules

chisel_p1:
  script:
    - ./test_processor.sh chisel_p1 #--full_ci
  tags: ["fpga"]
#  only:
#    - develop
  except:
    - schedules

chisel_p2:
  script:
    - ./test_processor.sh chisel_p2
  tags: ["fpga-pcie"]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - debian/riscv64-chroot.tar
      - bootmem/
  only:
    variables:
      - $JOB_TYPE == "linux"

bluespec_p2:
  script:
    - ./test_processor.sh bluespec_p2
  tags: ["fpga-pcie"]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - debian/riscv64-chroot.tar
      - bootmem/
  only:
      variables:
      - $JOB_TYPE == "linux"

chisel_p3:
  script:
    - ./test_processor.sh chisel_p3
  tags: ["fpga-pcie"]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - debian/riscv64-chroot.tar
      - bootmem/
  only:
      variables:
      - $JOB_TYPE == "linux"

#bluespec_p3: # currently fails
#  script:
#    - ./test_processor.sh bluespec_p3
#  tags: ["fpga"]
#  only:
#      variables:
#      - $JOB_TYPE == "bluespec_p3"

testgen:
  stage: .post
  tags: ["fpga"]
  only:
    variables:
      - $PIPELINE_TYPE == "full"
  script:
    - "curl -X POST -F 'token=$TESTGEN_TRIGGER' -F 'ref=master' https://gitlab-ext.galois.com/api/v4/projects/273/trigger/pipeline"
  
