before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - echo $SSH_PRIVATE_KEY
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh git@gitlab-ext.galois.com
    - "./init_submodules.sh"

chisel_p1:
  script:
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh chisel_p1'"
  tags: ["fpga"]
  except:
    - schedules

bluespec_p1:
  script:
    - "nix-shell tool-suite/shell.nix --run './test_processor.sh bluespec_p1'"
  tags: ["fpga"]
  except:
    - schedules

