cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - riscv-linux/
    - busybox/

#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - ./init_submodules.sh

#-----------------------------------------------------------------------------#
#
# FPGA tests
#
#-----------------------------------------------------------------------------#
bluespec_p1:
  script:
    - source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh
    - nix-shell --run './test_processor.sh bluespec_p1 --full_ci'
  tags: ["fpga"]
  only:
    - ecats-develop
  except:
    - schedules

#-----------------------------------------------------------------------------#
#
# Bitstream generation
#
#-----------------------------------------------------------------------------#
bitstream_gen:
    script:
      - export XILINXD_LICENSE_FILE=/opt/Xilinx/Xilinx.lic
      - source /opt/Xilinx/Vivado/2017.4/settings64.sh
      - echo "Building bluespec_p1 bitstream"
      - nix-shell --run './setup_soc_project.sh bluespec_p1'
      - nix-shell --run './build.sh bluespec_p1'
      - echo "bluespec_p1 bitstream complete"
    tags: ["bitstream"]
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        when: always
        expire_in: 1 week
        paths:
            - bitstreams/soc_bluespec_p1.*
            - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_timing_summary_routed.rpt
            - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_utilization_placed.rpt
            - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_power_routed.rpt
    only:
      variables:
      - $JOB_TYPE == "bitstream"

