cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - riscv-linux/
    - busybox/

#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab-ext.galois.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ./init_submodules.sh

#-----------------------------------------------------------------------------#
#
# FreeRTOS compilation test
#
#-----------------------------------------------------------------------------#
FreeRTOS:
  script:
    - git clone https://github.com/mirror/busybox.git tmp
    - nix-shell --run './compilation_test.sh'
  tags: ["fpga"]
  only:
    - ecats-develop
  except:
    - schedules


#-----------------------------------------------------------------------------#
#
# FPGA tests
#
#-----------------------------------------------------------------------------#
bluespec_p1:
  script:
    - source /opt/Xilinx/Vivado_Lab/2017.4/settings64.sh
    - nix-shell --run './test_processor.sh bluespec_p1 --full_ci'
  tags: ["fpga"]
  only:
    - ecats-develop
  except:
    - schedules


#-----------------------------------------------------------------------------#
#
# Bitstream generation
#
#-----------------------------------------------------------------------------#
bitstream_gen:
    script:
      - export XILINXD_LICENSE_FILE=/opt/Xilinx/Xilinx.lic
      - source /opt/Xilinx/Vivado/2017.4/settings64.sh
      - echo "Building bluespec_p1 bitstream"
      - nix-shell --run './setup_soc_project.sh bluespec_p1'
      - nix-shell --run './build.sh bluespec_p1'
      - echo "bluespec_p1 bitstream complete"
    tags: ["bitstream"]
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        when: always
        expire_in: 1 week
        paths:
            - bitstreams/soc_bluespec_p1.*
            - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_timing_summary_routed.rpt 
            - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_utilization_placed.rpt 
            - vivado/soc_bluespec_p1/soc_bluespec_p1.runs/impl_1/design_1_power_routed.rpt 
    only:
      variables:
      - $JOB_TYPE == "bitstream"
