/*
 * Generated by Bluespec Compiler (build 67161ca2)
 * 
 */
#ifndef __vpi_wrapper_c_trace_file_close_h__
#define __vpi_wrapper_c_trace_file_close_h__

#include <vpi_user.h>

/* registration function */
void c_trace_file_close_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_trace_file_close_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_trace_file_close_h__ */
