/*
 * Generated by Bluespec Compiler (build 67161ca2)
 * 
 */
#ifndef __vpi_wrapper_bub_fifo_BDPI_Create_h__
#define __vpi_wrapper_bub_fifo_BDPI_Create_h__

#include <vpi_user.h>

/* registration function */
void bub_fifo_BDPI_Create_vpi_register();

/* VPI wrapper function */
PLI_INT32 bub_fifo_BDPI_Create_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_bub_fifo_BDPI_Create_h__ */
